/** 
 * File Name: layout.tsx
 * Purpose: Defines the RootLayout component as a fundamental HTML structure wrapper for Next.js application pages, providing a standardized layout across the application. It also exports metadata for the application, including title and description, potentially for SEO or informational purposes.
 * Created Date: 2024-03-14 
 */

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
